services:
  kimai:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      # Database connection - Using AWS RDS MySQL
      DATABASE_URL: ${DATABASE_URL}

      # Initial admin user (created on first run)
      ADMINMAIL: ${ADMINMAIL:-admin@example.com}
      ADMINPASS: ${ADMINPASS:-changemeonlogin}

      # Application settings
      APP_SECRET: ${APP_SECRET}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-localhost,127.0.0.1}

      # Email settings (optional, can be configured later)
      MAILER_FROM: ${MAILER_FROM:-kimai@example.com}
      MAILER_URL: ${MAILER_URL:-null://null}

      # Webhook settings (optional)
      WEBHOOK_URL: ${WEBHOOK_URL:-}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET:-}

      # Notion integration (optional)
      NOTION_API_KEY: ${NOTION_API_KEY:-}
      NOTION_PROJECT_DATABASE_ID: ${NOTION_PROJECT_DATABASE_ID:-}
      NOTION_TIME_ENTRY_DATABASE_ID: ${NOTION_TIME_ENTRY_DATABASE_ID:-}
      NOTION_TASK_DATABASE_ID: ${NOTION_TASK_DATABASE_ID:-}
      NOTION_WORKSPACE: ${NOTION_WORKSPACE:-}
    volumes:
      # Only persist truly dynamic data
      - kimai_logs:/opt/kimai/var/logs
      - kimai_cache:/opt/kimai/var/cache
      - kimai_data:/opt/kimai/var/data
      - kimai_sessions:/opt/kimai/var/sessions

volumes:
  kimai_logs:
  kimai_cache:
  kimai_data:
  kimai_sessions:
